RESET_USERS_TABLE = "DELETE FROM users;"

# IF USER TABLE RESET MUST ADD THIS AS WELL OTHERWISE SERIAL ID WILL INCREMENT FROM THE LAST ID
RESET_USER_SEQ = "ALTER SEQUENCE users_id_seq RESTART WITH 1;"

RESET_TOKENS_TABLE = "DELETE FROM tokens;"

RESET_COURSES_TABLE = "DELETE FROM courses;"

RESET_COURSES_SEQ = "ALTER SEQUENCE courses_id_seq RESTART WITH 1;"

RESET_RESOURCES_TABLE = "DELETE FROM resources;"

RESET_RESOURCES_SEQ = "ALTER SEQUENCE resources_id_seq RESTART WITH 1;"

RESET_CLASSES_TABLE = "DELETE FROM classes;"

RESET_CLASSES_SEQ = "ALTER SEQUENCE classes_id_seq RESTART WITH 1;"

RESET_BADGES_TABLE = "DELETE FROM badges;"

RESET_USER_BADGES_TABLE = "DELETE FROM user_badges;"